### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by herokudev** [Maha-Magdy/space-travelers-hub#25]
You can access the GitHub project at this link:
[Space travel's Hub](https://github.com/Maha-Magdy/space-travelers-hub)

People participating in this project(2):
[Maha-Magdy](https://github.com/Maha-Magdy)
[Herokudev](https://github.com/herokudev)

**Comment by helman101** [comment]
# STATUS: CHANGES REQUIRED ♻️ 

Hi @herokudev  and @Maha-Magdy  👋, 

Nice work so far on this milestone of the project  😄, but there are still some changes to do.

### Required Changes ♻️

- [ ]  There are 2 members on your team, so I should see `17` cards only, currently, I'm seeing `27` cards, please follow the project requirements step by step.
- [ ] All cards should be assigned to a team member, right now any of the cards are assigned
    - It should look something like this:
    ![image](https://user-images.githubusercontent.com/60789317/136836509-a707a183-533c-4fcf-b37a-9b99382d3ea6.png)
    - Yours look like this (No circle with photo):
    ![image](https://user-images.githubusercontent.com/60789317/136836694-f9fa2cd0-394e-435d-8fab-aebef27a8a5b.png)
- [ ] It is required for each team member to have assigned a card of each of these categories `Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters`
- [ ] Remember that the task should be distributed in a fair way. 😄 

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by herokudev** [comment]
Suggested changes done!

**Comment by herokudev** [comment]
ok, ready to submit
